import { auth } from "@clerk/nextjs/server";
import Link from "next/link";
import { FileText, HardDrive, Plus } from "lucide-react";
import { DeleteDocument } from "@/components/documents/delete-document";
import { listDocuments } from "@/lib/db/queries";

const BLOB_ALLOWANCE_BYTES = 1024 * 1024 * 1024;

export default async function DocumentsPage() {
  const { userId } = await auth(); const documents = userId ? await listDocuments(userId) : [];
  const storedBytes = documents.reduce((total, document) => total + document.size, 0); const remainingBytes = Math.max(BLOB_ALLOWANCE_BYTES - storedBytes, 0); const toMb = (bytes: number) => `${(bytes / 1024 / 1024).toFixed(bytes > 100 * 1024 * 1024 ? 0 : 1)} MB`;
  return <div className="mx-auto max-w-5xl px-5 pb-24 pt-12 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow">Source registry</p><h1 className="display mt-3 text-5xl sm:text-6xl">Documents</h1></div><Link href="/upload" className="primary-action flex items-center gap-2 rounded-full px-4 py-2 text-sm font-semibold"><Plus size={16}/>Ingest PDF</Link></div><section className="mt-10 grid gap-px border-y border-[#d9dfdc] py-5 sm:grid-cols-[1fr_auto]"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-[#e8f5f2] text-[#16756a]"><HardDrive size={18}/></span><div><p className="font-semibold">Private source storage</p><p className="text-sm text-[#60717a]">{toMb(storedBytes)} used by saved PDFs</p></div></div><p className="self-center text-sm font-semibold text-[#16756a]">About {toMb(remainingBytes)} left of 1 GB</p></section><div className="border-t border-[#d9dfdc]">{documents.length ? documents.map((document) => <article key={document.id} className="flex flex-wrap items-center justify-between gap-4 border-b border-[#d9dfdc] py-5"><Link href={`/documents/${document.id}`} className="flex min-w-0 items-center gap-4"><span className="grid size-10 shrink-0 place-items-center bg-[#e8f5f2] text-[#16756a]"><FileText size={19}/></span><span className="min-w-0"><span className="block truncate font-semibold hover:underline">{document.title}</span><span className="mt-1 block truncate text-sm text-[#60717a]">Original: {document.originalFileName} · {toMb(document.size)} · {document.questionCount ?? 0} questions</span></span></Link><DeleteDocument id={document.id} title={document.title}/></article>) : <div className="py-20 text-center"><FileText className="mx-auto text-[#9aa8a5]"/><p className="display mt-4 text-3xl">No saved study sources yet.</p><p className="mt-2 text-[#60717a]">Name and save a generated set to keep its private PDF and question bank here.</p></div>}</div></div>;
}
