import type { CaseStudy, Question, Specialty } from "@/lib/domain/types";

export const specialties: Specialty[] = [
  { id: "thoracic", slug: "thoracic", name: "Thoracic surgery", description: "Resection, drains, pulmonary recovery", color: "#2a9d8f" },
  { id: "breast", slug: "breast", name: "Breast surgery", description: "Oncoplastic care and lymphatic risk", color: "#d57a66" },
  { id: "thyroid", slug: "thyroid", name: "Thyroid surgery", description: "Airway, calcium, voice and recovery", color: "#e5a844" },
  { id: "pulmonary_htn", slug: "pulmonary-htn", name: "Pulmonary hypertension", description: "Haemodynamics and functional capacity", color: "#6987b8" },
  { id: "heart_failure", slug: "heart-failure", name: "Heart failure", description: "Congestion, monitoring and rehabilitation", color: "#b35b70" },
  { id: "ihd", slug: "ihd", name: "Ischaemic heart disease", description: "Acute presentation and secondary prevention", color: "#b47c51" },
  { id: "abdominal", slug: "abdominal", name: "Abdominal surgery", description: "Enhanced recovery and surgical complications", color: "#77966d" },
];

export const benchmarkCases: CaseStudy[] = [
  { id: "00000000-0000-4000-8000-000000000001", title: "Day two after a right upper lobectomy", specialty: "thoracic", summary: "A 68-year-old develops increasing breathlessness and guarded coughing while a chest drain remains in situ.", learningPoints: ["Chest drain review", "Supported cough", "Early mobilisation"], rehabPlan: "Mobilise with monitoring, teach thoracic expansion and supported cough, then progress walking distance as oxygenation permits." },
  { id: "00000000-0000-4000-8000-000000000002", title: "Recovery after axillary clearance", specialty: "breast", summary: "A patient reports shoulder stiffness and concern about arm swelling at an early postoperative review.", learningPoints: ["Range restoration", "Lymphoedema awareness", "Scar and posture care"], rehabPlan: "Stage shoulder mobility within surgical precautions; establish posture, gentle range and escalation criteria for swelling or wound changes." },
  { id: "00000000-0000-4000-8000-000000000003", title: "Neck symptoms after thyroidectomy", specialty: "thyroid", summary: "A patient experiences paraesthesia and hoarseness in the hours after surgery.", learningPoints: ["Urgent recognition", "Airway observation", "Calcium symptoms"], rehabPlan: "Prioritise escalation of red flags before routine mobility. Reinforce breathing, neck comfort and safe return to activity after stability." },
  { id: "00000000-0000-4000-8000-000000000004", title: "Mobilising after open laparotomy", specialty: "abdominal", summary: "A 59-year-old is reluctant to move due to pain on the first day after an uncomplicated bowel resection.", learningPoints: ["Enhanced recovery", "Pain-aware mobility", "Pulmonary prevention"], rehabPlan: "Coordinate analgesia, use log-roll and supported cough techniques, then mobilise in short frequent doses with clear functional goals." },
];

export const coreQuestions: Question[] = [
  { id: "00000000-0000-4000-8000-000000000011", specialty: "thoracic", stem: "Following a thoracotomy, which intervention most directly supports clearance of retained secretions when pain limits coughing?", options: ["Supported huff and cough practice", "Strict bed rest", "Fluid restriction", "Avoiding all shoulder movement"], correctIndex: 0, rationale: "A supported huff and cough helps secretion clearance while protecting the incision. Bed rest and avoiding movement increase postoperative pulmonary risk; fluid restriction is not a physiotherapy secretion strategy.", focus: "physio_management", difficulty: "undergrad", complicationTiming: null, sourceCitation: "Core thoracic rehabilitation: supported cough and early mobilisation", documentId: null },
  { id: "00000000-0000-4000-8000-000000000012", specialty: "breast", stem: "A patient after axillary surgery reports progressive arm heaviness. Which finding should prompt assessment for a postoperative lymphatic complication?", options: ["Unilateral arm swelling", "Improved shoulder range", "Transient hunger", "Warm feet after walking"], correctIndex: 0, rationale: "Unilateral swelling and heaviness are relevant warning signs after axillary intervention. The other findings do not indicate lymphatic dysfunction.", focus: "surgical_complication", difficulty: "undergrad", complicationTiming: "late", sourceCitation: "Core breast surgery: lymphoedema surveillance", documentId: null },
  { id: "00000000-0000-4000-8000-000000000013", specialty: "thyroid", stem: "Hours after thyroid surgery, a patient develops tingling around the mouth and in both hands. Which postoperative problem is most consistent with this pattern?", options: ["Hypocalcaemia", "A superficial skin bruise", "Constipation", "Shoulder impingement"], correctIndex: 0, rationale: "Perioral and hand paraesthesia are classic signs requiring review for postoperative hypocalcaemia. The distractors do not account for this characteristic bilateral sensory pattern.", focus: "diagnostic", difficulty: "undergrad", complicationTiming: "early", sourceCitation: "Core thyroid surgery: calcium-related symptom monitoring", documentId: null },
  { id: "00000000-0000-4000-8000-000000000014", specialty: "pulmonary_htn", stem: "For a patient with pulmonary hypertension starting an activity programme, which principle best supports safe rehabilitation planning?", options: ["Monitor symptoms and progress gradually", "Prescribe maximal effort immediately", "Ignore breathlessness during exercise", "Avoid all functional activity"], correctIndex: 0, rationale: "Gradual progression with symptom monitoring supports safe functional conditioning. Maximal unmonitored effort and complete avoidance are both inappropriate extremes.", focus: "physio_management", difficulty: "postgrad", complicationTiming: null, sourceCitation: "Core pulmonary hypertension: graded functional activity", documentId: null },
  { id: "00000000-0000-4000-8000-000000000015", specialty: "heart_failure", stem: "Which change most strongly suggests fluid congestion in a person with established heart failure?", options: ["Rapid weight increase with ankle swelling", "Improved exercise tolerance", "Reduced appetite after a meal", "A new haircut"], correctIndex: 0, rationale: "Rapid weight gain alongside peripheral oedema is a useful congestion pattern. The other responses do not identify fluid accumulation.", focus: "diagnostic", difficulty: "undergrad", complicationTiming: null, sourceCitation: "Core heart failure: congestion self-monitoring", documentId: null },
  { id: "00000000-0000-4000-8000-000000000016", specialty: "ihd", stem: "During cardiac rehabilitation education, which feature makes chest discomfort more concerning for myocardial ischaemia?", options: ["It is provoked by exertion and eases with rest", "It occurs only while asleep after a large meal", "It improves when the patient worries", "It follows a trivial finger cut"], correctIndex: 0, rationale: "Exertional discomfort relieved by rest is a recognisable anginal pattern. The other options are not characteristic descriptions of exertional myocardial ischaemia.", focus: "diagnostic", difficulty: "postgrad", complicationTiming: null, sourceCitation: "Core IHD: exertional symptom pattern", documentId: null },
  { id: "00000000-0000-4000-8000-000000000017", specialty: "abdominal", stem: "On the first day after open abdominal surgery, which approach best reduces pulmonary and functional complications?", options: ["Pain-aware early mobilisation with breathing practice", "Remaining supine all day", "Withholding all fluids without review", "Avoiding coughs entirely"], correctIndex: 0, rationale: "Early, pain-aware mobility combined with respiratory practice supports recovery. Prolonged immobility and cough avoidance increase postoperative risk.", focus: "physio_management", difficulty: "undergrad", complicationTiming: "early", sourceCitation: "Core abdominal enhanced recovery: early mobilisation", documentId: null },
];
