"use client";

import { useState } from "react";
import { ArrowRight, CheckCircle2, RotateCcw } from "lucide-react";
import type { Question } from "@/lib/domain/types";
import { cn } from "@/lib/utils";

export function QuizPlayer({ questions }: { questions: Question[] }) {
  const [index, setIndex] = useState(0); const [selected, setSelected] = useState<number | null>(null); const [answers, setAnswers] = useState<number[]>([]);
  const question = questions[index];
  if (!question) return <div className="border border-dashed border-[#b9c8c3] p-10 text-center"><p className="display text-3xl">No questions match this set.</p><p className="mt-2 text-[#60717a]">Return to the question bank and choose a different filter.</p></div>;
  const completed = answers.length === questions.length;
  const score = answers.reduce((total, answer, answerIndex) => total + (answer === questions[answerIndex].correctIndex ? 1 : 0), 0);
  function next() { if (selected === null) return; setAnswers([...answers, selected]); setSelected(null); setIndex(index + 1); }
  if (completed) return <section className="mx-auto max-w-2xl py-16 text-center"><CheckCircle2 className="mx-auto text-[#2a9d8f]" size={48}/><p className="eyebrow mt-5">Session complete</p><h1 className="display mt-3 text-6xl">{score}/{questions.length}</h1><p className="mt-4 text-[#60717a]">Review the source-linked teaching notes, then repeat this document set to consolidate weak areas.</p><button onClick={() => { setIndex(0); setAnswers([]); setSelected(null); }} className="primary-action mx-auto mt-8 flex items-center gap-2 rounded-full px-5 py-3 text-sm font-semibold"><RotateCcw size={16}/>Restart session</button></section>;
  return <section className="mx-auto max-w-3xl py-10"><div className="mb-8 flex items-center justify-between text-sm"><span className="eyebrow">Question {index + 1} of {questions.length}</span><span className="text-[#60717a]">{answers.filter((answer, i) => answer === questions[i].correctIndex).length} correct</span></div><div className="h-1 overflow-hidden bg-[#d9dfdc]"><div className="h-full bg-[#2a9d8f] transition-all" style={{ width: `${(index / questions.length) * 100}%` }}/></div><p className="mt-8 text-xs font-bold uppercase tracking-widest text-[#60717a]">{question.specialty.replaceAll("_", " ")} · {question.difficulty}</p><h1 className="display mt-4 text-4xl leading-tight sm:text-5xl">{question.stem}</h1><div className="mt-9 grid gap-3">{question.options.map((option, optionIndex) => <button key={option} onClick={() => setSelected(optionIndex)} className={cn("flex gap-4 border p-5 text-left transition", selected === optionIndex ? "border-[#2a9d8f] bg-[#e8f5f2]" : "border-[#d9dfdc] bg-white hover:border-[#7daaa2]")}><span className="font-semibold text-[#2a9d8f]">{String.fromCharCode(65 + optionIndex)}</span>{option}</button>)}</div>{selected !== null && <div className="fade-up mt-5 border-l-2 border-[#2a9d8f] bg-[#edf5f2] p-4 text-sm leading-6"><strong>{selected === question.correctIndex ? "Correct. " : "Not quite. "}</strong>{question.rationale}</div>}<button disabled={selected === null} onClick={next} className="ml-auto mt-7 flex items-center gap-2 rounded-full bg-[#0b1f2a] px-5 py-3 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40">{index + 1 === questions.length ? "Finish session" : "Next question"}<ArrowRight size={16}/></button></section>;
}
